modLoader = "javafml"
loaderVersion = "[3,)"
license = "LGPLv3"

[[mods]]
modId = "krypton"
version = "${version}"
displayName = "KryptonFoxified"
displayURL="https://github.com/ThinkingStudios/Krypton-Foxified" #optional
logoFile="icon.png" #optional
credits="tuxed" #optional
authors="TexTrue, ThinkingStudio" #optional
description = '''
Krypton unofficial NeoForge port.

A mod that optimizes the Minecraft networking stack and entity tracker.
'''

[[mixins]]
config = "krypton.mixins.json"

[[dependencies.krypton]]
modId = "neoforge"
type = "required"
versionRange = "[20.5,20.6]"
ordering = "NONE"
side = "SERVER"

[[dependencies.krypton]]
modId = "minecraft"
type = "required"
versionRange = "[1.20.5,1.20.6]"
ordering = "NONE"
side = "SERVER"